# Generated by Django 3.2.4 on 2021-06-10 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remesh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['start_date', 'title']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='thought',
            options={'ordering': ['time']},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='remesh.conversation'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='thought',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thoughts', to='remesh.message'),
        ),
        migrations.AlterField(
            model_name='thought',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
